# Generated by Django 3.0.5 on 2020-07-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cubecomment',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
