# Generated by Django 3.0.5 on 2020-07-29 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubes', '0002_cubecomment_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cubecomment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cubecomment',
            name='updated_at',
        ),
    ]
