# Generated by Django 3.0.5 on 2020-07-29 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubes', '0005_auto_20200729_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cubecomment',
            name='order',
        ),
    ]
