# Generated by Django 3.0.5 on 2020-07-29 04:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cubes', '0006_remove_cubecomment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cubecomment',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
