# Generated by Django 3.0.5 on 2020-07-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubes', '0007_auto_20200729_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cubecomment',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cubecomment',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
