# Generated by Django 3.0.5 on 2020-05-25 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cubes', '0001_initial'),
        ('tiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tilecomment',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='tilecomment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cubes.CubeComment'),
        ),
    ]
