# Generated by Django 3.0.5 on 2020-07-24 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cubes', '0001_initial'),
        ('tiles', '0003_auto_20200526_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('follow', models.BooleanField(default=False, null=True)),
                ('favorite', models.BooleanField(default=False, null=True)),
                ('comment', models.BooleanField(default=False, null=True)),
                ('post', models.BooleanField(default=False, null=True)),
                ('new_notification', models.BooleanField(default=True, null=True)),
                ('content', models.CharField(max_length=255)),
                ('type', models.IntegerField()),
                ('From', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from+', to=settings.AUTH_USER_MODEL)),
                ('To', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to+', to=settings.AUTH_USER_MODEL)),
                ('cube', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cubes.Cube')),
                ('tile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tiles.Tile')),
            ],
            options={
                'db_table': 'history',
            },
        ),
    ]
