# Generated by Django 3.0.5 on 2020-07-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0006_auto_20200729_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='link',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tile',
            name='photo_url',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tile',
            name='sequence',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tilecomment',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
