# Generated by Django 2.2.15 on 2020-08-25 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0009_auto_20200820_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='content',
        ),
        migrations.RemoveField(
            model_name='history',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='history',
            name='follow',
        ),
        migrations.RemoveField(
            model_name='history',
            name='post',
        ),
    ]
