# Generated by Django 2.2.15 on 2020-11-23 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0010_auto_20200825_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='thumb_url',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
